apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-comportado
  name: pod-comportado
  namespace: treinamento-ch2
spec:
  containers:
  - image: polinux/stress
    name: pod-comportado
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "300Mi"

